title: "Seth Lu's Blog"
author: "Seth Lu"
description: "Experiments and thoughts on quantitative trading"

theme: jekyll-theme-dinky

markdown: kramdown
kramdown:
  math_engine: mathjax













