title: "Quantitative Trading Blog"
author: "Seth Lu"
description: "Experiments and thoughts on trading."

theme: jekyll-theme-dinky

markdown: kramdown
kramdown:
  math_engine: mathjax












